version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Install Docker CLI
          command: |
            if ! command -v docker >/dev/null; then
              sudo apt-get update && sudo apt-get install -y docker.io
            fi
            docker --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install Python deps (venv)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run hadolint via Makefile
          command: |
            . venv/bin/activate || true
            make lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
