version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker CLI
          command: |
            if ! command -v docker >/dev/null; then
              sudo apt-get update && sudo apt-get install -y docker.io
            fi
      - run:
          name: Run lint (dockerized hadolint)
          command: make lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
